baseURL = "https://github.com/JorgeGuillen7/my_launchx_blog"
languageCode = "en-us"
title = "Bitácora de Viaje de Amauri Guillén"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu twitter 👇
  # twitter_handle = "@micuentadetwitter"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
